from pathlib import Path
p=Path('Money/Views/SettingsAndData/DataOperationsPage.xaml.cs');s=p.read_text(encoding='utf-8-sig')
s=s.replace('            if (account is null)\n                throw new InvalidDataException("Cadastre uma conta antes da importação.");','')
s=s.replace('            var category = categories.FirstOrDefault(x => x.Type == type && Normalize(x.Name) == Normalize(Cell(row, "categoria")))\n                ?? categories.FirstOrDefault(x => x.Type == type);','            var category = type == "transferencia" ? null : DatabaseService.ResolveImportedSubcategory(categories.Where(x=>x.Type==type), Cell(row,"categoria"), Cell(row,"subcategoria"));')
s=s.replace('category?.Id ?? 0, account.Id,','category?.Id ?? 0, null,')
s=s.replace('        var account = accounts.FirstOrDefault() ?? throw new InvalidDataException("Cadastre uma conta antes da importação.");','')
s=s.replace('            var category = categories.FirstOrDefault(x => x.Type == type) ?? throw new InvalidDataException($"Cadastre uma categoria de {type}.");','            var category = DatabaseService.ResolveImportedSubcategory(categories.Where(x=>x.Type==type), type=="despesa"?"Outros":"Receitas",type=="despesa"?"Outras Despesas":"Outras Receitas");')
s=s.replace('type, category.Id, account.Id, null, $"OFX FITID: {Tag("FITID")}"','type, category.Id, null, null, $"Classificação automática: {category.DisplayName}. OFX FITID: {Tag("FITID")}"')
p.write_text(s,encoding='utf-8')
p=Path('Money/Services/DatabaseService.cs');s=p.read_text(encoding='utf-8-sig')
s=s.replace("SELECT id_categoria FROM Categorias WHERE id_usuario=@user AND tipo='despesa' AND ativo=1 ORDER BY id_categoria LIMIT 1", "SELECT c.id_categoria FROM Categorias c JOIN CategoriaPilar p ON p.id_categoria_pilar=c.id_categoria_pilar AND p.id_usuario=c.id_usuario WHERE c.id_usuario=@user AND c.tipo='despesa' AND c.ativo=1 AND p.ativo=1 AND p.nome_normalizado='OUTROS' AND c.nome_normalizado='OUTRAS DESPESAS'")
p.write_text(s,encoding='utf-8')
p=Path('Money/Services/ReportPdfService.cs');s=p.read_text(encoding='utf-8-sig').replace('items.GroupBy(x => x.Category)','items.GroupBy(x => x.MainCategory)').replace('Text(item.Category)','Text(item.Subcategory)').replace('Text("CATEGORIA")','Text("SUBCATEGORIA")');p.write_text(s,encoding='utf-8')
p=Path('Money/Platforms/Android/ProfessionalReportPdfRenderer.cs');s=p.read_text(encoding='utf-8-sig').replace('items.GroupBy(item => item.Category)','items.GroupBy(item => item.MainCategory)');s=s.replace('Text(Cut(item.Description, 27)', 'Text(Cut(item.Subcategory + ": " + item.Description, 27)');p.write_text(s,encoding='utf-8')
