-- Material Icons dinâmicos para todas as categorias do moneypro.db.
UPDATE Categorias SET icone='restaurant' WHERE nome_categoria='Alimentação';
UPDATE Categorias SET icone='shopping_cart' WHERE nome_categoria='Supermercado';
UPDATE Categorias SET icone='restaurant' WHERE nome_categoria='Restaurantes';
UPDATE Categorias SET icone='fastfood' WHERE nome_categoria='Lanches';
UPDATE Categorias SET icone='home' WHERE nome_categoria IN ('Moradia','Casa');
UPDATE Categorias SET icone='key' WHERE nome_categoria='Aluguel';
UPDATE Categorias SET icone='apartment' WHERE nome_categoria='Condomínio';
UPDATE Categorias SET icone='bolt' WHERE nome_categoria='Energia Elétrica';
UPDATE Categorias SET icone='water_drop' WHERE nome_categoria='Água';
UPDATE Categorias SET icone='propane_tank' WHERE nome_categoria='Gás';
UPDATE Categorias SET icone='wifi' WHERE nome_categoria='Internet';
UPDATE Categorias SET icone='phone' WHERE nome_categoria='Telefone';
UPDATE Categorias SET icone='smartphone' WHERE nome_categoria='Celular';
UPDATE Categorias SET icone='chair' WHERE nome_categoria='Móveis';
UPDATE Categorias SET icone='deck' WHERE nome_categoria='Decoração';
UPDATE Categorias SET icone='build' WHERE nome_categoria='Manutenção Residencial';
UPDATE Categorias SET icone='directions_car' WHERE nome_categoria='Transporte';
UPDATE Categorias SET icone='local_gas_station' WHERE nome_categoria='Combustível';
UPDATE Categorias SET icone='car_repair' WHERE nome_categoria='Manutenção Veículo';
UPDATE Categorias SET icone='shield' WHERE nome_categoria='Seguro Veículo';
UPDATE Categorias SET icone='directions_bus' WHERE nome_categoria='Transporte Público';
UPDATE Categorias SET icone='local_taxi' WHERE nome_categoria='Uber / Táxi';
UPDATE Categorias SET icone='favorite' WHERE nome_categoria='Saúde';
UPDATE Categorias SET icone='local_pharmacy' WHERE nome_categoria='Farmácia';
UPDATE Categorias SET icone='medical_services' WHERE nome_categoria IN ('Plano de Saúde','Consultas Médicas','Veterinário');
UPDATE Categorias SET icone='science' WHERE nome_categoria='Exames';
UPDATE Categorias SET icone='fitness_center' WHERE nome_categoria='Academia';
UPDATE Categorias SET icone='school' WHERE nome_categoria IN ('Educação','Mensalidade Escolar');
UPDATE Categorias SET icone='cast_for_education' WHERE nome_categoria='Cursos';
UPDATE Categorias SET icone='menu_book' WHERE nome_categoria='Livros';
UPDATE Categorias SET icone='edit_note' WHERE nome_categoria='Material Escolar';
UPDATE Categorias SET icone='attractions' WHERE nome_categoria='Lazer';
UPDATE Categorias SET icone='movie' WHERE nome_categoria='Cinema';
UPDATE Categorias SET icone='flight' WHERE nome_categoria='Viagens';
UPDATE Categorias SET icone='explore' WHERE nome_categoria='Passeios';
UPDATE Categorias SET icone='live_tv' WHERE nome_categoria='Streaming';
UPDATE Categorias SET icone='sports_esports' WHERE nome_categoria='Jogos';
UPDATE Categorias SET icone='shopping_bag' WHERE nome_categoria IN ('Compras','ComprasMaria','ComprasYago');
UPDATE Categorias SET icone='checkroom' WHERE nome_categoria='Roupas';
UPDATE Categorias SET icone='steps' WHERE nome_categoria='Calçados';
UPDATE Categorias SET icone='watch' WHERE nome_categoria='Acessórios';
UPDATE Categorias SET icone='devices' WHERE nome_categoria='Eletrônicos';
UPDATE Categorias SET icone='computer' WHERE nome_categoria='Informática';
UPDATE Categorias SET icone='miscellaneous_services' WHERE nome_categoria='Serviços';
UPDATE Categorias SET icone='cleaning_services' WHERE nome_categoria='Serviços Domésticos';
UPDATE Categorias SET icone='local_laundry_service' WHERE nome_categoria='Lavanderia';
UPDATE Categorias SET icone='subscriptions' WHERE nome_categoria='Assinaturas';
UPDATE Categorias SET icone='receipt_long' WHERE nome_categoria IN ('Taxas','Impostos','Multas');
UPDATE Categorias SET icone='account_balance' WHERE nome_categoria='Tarifas Bancárias';
UPDATE Categorias SET icone='groups' WHERE nome_categoria='Consórcios';
UPDATE Categorias SET icone='volunteer_activism' WHERE nome_categoria IN ('Doações','Dizimo');
UPDATE Categorias SET icone='card_giftcard' WHERE nome_categoria='Presentes';
UPDATE Categorias SET icone='pets' WHERE nome_categoria IN ('Animais de Estimação','Pet Shop');
UPDATE Categorias SET icone='payments' WHERE nome_categoria IN ('Salário','Adiantamento Salarial','Mesada');
UPDATE Categorias SET icone='more_time' WHERE nome_categoria='Horas Extras';
UPDATE Categorias SET icone='work' WHERE nome_categoria IN ('Comissões','Freelance','Trabalho Autônomo');
UPDATE Categorias SET icone='card_giftcard' WHERE nome_categoria IN ('Bônus','Bonificações','Prêmios');
UPDATE Categorias SET icone='celebration' WHERE nome_categoria IN ('Décimo Terceiro','Férias');
UPDATE Categorias SET icone='storefront' WHERE nome_categoria IN ('Venda de Produtos','Venda de Serviços','Venda de Bens');
UPDATE Categorias SET icone='real_estate_agent' WHERE nome_categoria='Aluguel Recebido';
UPDATE Categorias SET icone='trending_up' WHERE nome_categoria IN ('Dividendos','Rendimentos de Investimentos','Resgate de Investimentos');
UPDATE Categorias SET icone='percent' WHERE nome_categoria='Juros Recebidos';
UPDATE Categorias SET icone='savings' WHERE nome_categoria='Cashback';
UPDATE Categorias SET icone='price_check' WHERE nome_categoria IN ('Restituição de Imposto','Reembolso','Indenizações');
UPDATE Categorias SET icone='family_restroom' WHERE nome_categoria IN ('Ajuda Familiar','Doações Recebidas');
UPDATE Categorias SET icone='inventory_2' WHERE nome_categoria='Herança';
UPDATE Categorias SET icone='cell_tower' WHERE nome_categoria='iConnect';
UPDATE Categorias SET icone='account_box' WHERE nome_categoria='YagoContas';
UPDATE Categorias SET icone='category' WHERE nome_categoria LIKE '%Outros%' OR nome_categoria LIKE '%Outras%';
